### ISSUE TITLE
Request to Add Function Record Param Documentation Details

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#168]
Hello,

Would you please consider updating this page to include details on how to document the expected/allowed field structure for a record parameter to a function?

For example, Sql.Database's third argument is an optional record. As the below screenshot shows, the auto-generated function invocation form doesn't simply "know" that a record is expected, but also knows which fields are allowed to be present in the expected record. Would you consider revising this page to describe how users can provide these details for functions they want to document?

![image](https://user-images.githubusercontent.com/857202/134067072-52fe2c13-25c6-455a-ad2b-6f8cbffa6075.png)

Reference on how to document record shape: https://bengribaudo.com/blog/2021/09/21/6179/describing-function-record-parameters

Thank you,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a834875-02f7-683d-5845-618a5d02d888
* Version Independent ID: 36b3e58d-e580-a9fd-4239-7d51b24fdeb6
* Content: [Adding function documentation](https://docs.microsoft.com/en-us/power-query/handlingdocumentation)
* Content Source: [powerquery-docs/HandlingDocumentation.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingDocumentation.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
