### ISSUE TITLE
Link Request

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerquery-docs#221]
Hello,

Any chance a link to this page and/or a summary of these behaviors could be added to [Web.Contents](https://docs.microsoft.com/en-us/powerquery-m/web-contents)? This would make it easier for someone who goes there to learn about these behaviors.

Thanks,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0c5979-06ba-056e-6d69-07911a04761a
* Version Independent ID: 0c877e8f-db6e-eed7-871a-6abc4845f88a
* Content: [Handling status codes with Web.Contents for Power Query connectors - Power Query](https://docs.microsoft.com/en-us/power-query/handlingstatuscodes)
* Content Source: [powerquery-docs/HandlingStatusCodes.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/HandlingStatusCodes.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bgribaudo 
Thanks, for the feedback! Sorry it took so long for us to get to this issue. After discussions with the devs, we decided not to add this link. The link would point to an article that's only used by custom connector authors. Since the vast majority of readers will be regular users, not custom connector authors, the link isn't necessary.

**Comment by bgribaudo** [comment]
Hi @DougKlopfenstein,
Thank you for considering this suggestion and for letting me know. I appreciate all the work you and the team do on docs!
