### ISSUE TITLE
Documentation is not accurate: PowerPlatflow Analytical dataflow can be stored in Dataverse

### ISSUE THREAD

**Issue by MichaelDotEarly** [MicrosoftDocs/powerquery-docs#238]
[Enter feedback here]

It seems that this document is not accurate, at least on the table documenting the Standard Vs Analytical differences.

If you create a dataflow in PowerPlatform, when choosing Analytical you can actually choose Dataverse as storage solution.....
![image](https://user-images.githubusercontent.com/39583574/161794447-17a6329d-a802-463f-95ef-180056281c07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08c29a4-99c2-69ca-6bcd-75541c697215
* Version Independent ID: 0516d7ae-4cf4-a5e7-d20a-e3839ecf6120
* Content: [Understanding the differences between dataflow types - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/understanding-differences-between-analytical-standard-dataflows)
* Content Source: [powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/understanding-differences-between-analytical-standard-dataflows.md)
* Service: **powerquery**
* GitHub Login: @radacad
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @MichaelDotEarly 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. 

Because the referenced apps no longer work in the manner described in this issue, we are closing this issue for now. However, if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
