### ISSUE TITLE
Linked entities do not "link" with power platform connector

### ISSUE THREAD

**Issue by bslattz** [MicrosoftDocs/powerquery-docs#245]
[Enter feedback here]
Using the power platform conector does not link the entities.  It doesn't show in lineage and it does not orchestrate refreshes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d74d7-1c4b-310e-e381-c5ef6de14f65
* Version Independent ID: d8532777-57e4-51b1-306f-29cd3178bfda
* Content: [Link entities between dataflows - Power Query](https://docs.microsoft.com/en-us/power-query/dataflows/linked-entities)
* Content Source: [powerquery-docs/dataflows/linked-entities.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/linked-entities.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add tags). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @bslattz 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Since this issue was created, we've made several updates to the referred article. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
