### ISSUE TITLE
Issues when authentication is OAuth2

### ISSUE THREAD

**Issue by Neeeeena** [MicrosoftDocs/powerquery-docs#29]
This will ruin the authentication when this is OAuth2 as expired access codes will result in a 500 status code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e8ea07-c37a-f246-dc5b-ef434f4b097b
* Version Independent ID: cf8ff1f9-617a-a605-fad0-28e81123a660
* Content: [Using the wait-retry pattern in Power Query connectors](https://docs.microsoft.com/en-us/power-query/waitretry#feedback)
* Content Source: [powerquery-docs/WaitRetry.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/WaitRetry.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by mattmasson** [comment]
The same uses a `500` status as an example. Your connector code should use whichever status values are appropriate for your API. 

For what it's worth, service implementations vary, but expired OAuth token related errors should probably be returned as a `401` or `403` since these would indicate a credential problem. `500` typically means "an unexpected internal service error".
