### ISSUE TITLE
Add troubleshooting section for Datetime columns

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerquery-docs#296]
Hi MS Docs Admins,

Quite few users in our organization are confused with the date columns from SharePoint list when loading them in Power Query (Power BI). Due to the fact that Power Query reads datetime columns in UTC (as they truly are stored) while users see slightly different date in the browser when viewing SHP List. It would help me (as Power BI Admin in our organization) if I could point users to MS Docs where the difference between datetime in PQ and browser is explained, instead of pointing them to StackOverflow or Power BI Community posts. As this is a standard behaviour, I believe it should be part of the MS Docs.

Thank you beforehand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb18ebe3-3508-c988-a36e-6e40aaae601c
* Version Independent ID: a73c6ef2-5987-b4af-1596-f4bae458c7b7
* Content: [Power Query SharePoint list connector - Power Query](https://docs.microsoft.com/en-us/power-query/connectors/sharepointlist)
* Content Source: [powerquery-docs/Connectors/SharePointList.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointList.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **bezhan**

**Comment by JasonWHowell** [comment]
@MartinKDK thanks for the idea. We'll queue it up in our backlog.

**Comment by JasonWHowell** [comment]
@MartinKDK do you have a favorite post/answer to explain this? If you do, you may even edit the page and add a summary to explain it. The docs here are open source: https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/SharePointList.md

**Comment by DougKlopfenstein** [comment]
Hi @MartinKDK 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
