### ISSUE TITLE
Outdated. Incremental Refresh does not exist.

### ISSUE THREAD

**Issue by laser-developer** [MicrosoftDocs/powerquery-docs#311]
Outdated. Incremental Refresh does not exist as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffc816e2-78f6-ca70-92a3-b2153461759d
* Version Independent ID: e6fec9a8-1c47-b739-5146-0fa717c4535e
* Content: [Using incremental refresh with dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/incremental-refresh)
* Content Source: [powerquery-docs/dataflows/incremental-refresh.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/incremental-refresh.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by JasonWHowell** [comment]
#assign:@bensack please see if this is a documentation bug

**Comment by JasonWHowell** [comment]
#assign:bensack

**Comment by DougKlopfenstein** [comment]
Hi @laser-developer 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. After review by the engineering team, it was determined that this issue is incorrect. Incremental refresh does exist for Dataflow Gen1 and is also correct in the other docs for best practices. Therefore, we are closing this issue. #please-close
