### ISSUE TITLE
Terminology and supported Synapse Analytics objects

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#335]
Regarding

>This connector supports access to all data in your Synapse workspace, including Synapse Serverless, Synapse on-demand, and Spark tables.

Questions:

1) What's "Synapse Serverless"? Is it the Serverless SQL Pools?
2) What's "Synapse on-demand"?
3) What about Lake Databases?
4) What about Dedicated SQL Pools?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Version Independent ID: 054662fb-66f6-d36d-6ba5-85fde75574b9
* Content: [Power Query Azure Synapse Analytics workspace connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/synapse)
* Content Source: [powerquery-docs/Connectors/Synapse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/Synapse.md)
* Service: **powerquery**
* GitHub Login: @miquelladeboer
* Microsoft Alias: **mideboer**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now due to its age. But if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
