### ISSUE TITLE
Supported authentication types

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#339]
Regarding

![image](https://user-images.githubusercontent.com/1765732/204701737-256566d7-f636-4798-bf6a-0ebdec2e3161.png)

I think the above are pulled from the SQL Server connector description. 

Although this connector actually uses the SQL Server description, I think the authentication types should be aligned to list just those that apply to the connector;s page, i.e. the ones that can be used with Azure Synapse Analytics. 

My understanding is that there are only 2 options: https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/sql-authentication?tabs=serverless

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f15da4f-8f22-3f68-165c-1bb0c4edc887
* Version Independent ID: 29d89981-6694-8b87-d5b6-614b8680cd90
* Content: [Power Query Azure Synapse Analytics (SQL DW) connector - Power Query](https://learn.microsoft.com/en-us/power-query/connectors/azuresqldatawarehouse)
* Content Source: [powerquery-docs/Connectors/AzureSQLDataWarehouse.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/Connectors/AzureSQLDataWarehouse.md)
* Service: **powerquery**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 

The authentication types shown in the summary table are all of the authentication types supported in Power Query for this specific connector. For Power Query Desktop, the supported authentication types are:

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40473364/c37df292-4013-47c1-b3ad-0c246a9f9379)

Note that although the name at the top of this dialog says "SQL Server database", this is the authentication dialog for Azure Synapse Analytics (SQL DW).

For Power Query Online, the supported authentication types are:

![image](https://github.com/MicrosoftDocs/powerquery-docs/assets/40473364/2221a8e3-4ae5-4dce-aedd-010413c59833)

The list is out of date because "Service principal" isn't currently on the list. The list will be updated soon.

I'm closing the issue for now. However, if you have more information you would like to provide, please feel free to reopen the issue.

**Comment by VitalyMCT** [comment]
@DougKlopfenstein 

I think there are issues here beyond the missing "Service principal" option:

The screenshot I've included in the original ticket shows that the documentation page lists "Windows" as a supported authentication type for Synapse. This is incorrect. It's unfeasible to authenticate to Synapse via Windows authentication (from either PQ Desktop or PQ Web). Hence this page needs to be corrected accordingly to remove "Windows".

That's really the entire premise of this ticket. The SQL Server connector is shared, yes. However, this page is specifically for Synapse. It should thus exclude options that are covered by the same connector for SQL Server (or for Azure SQL Database, or for any other Microsoft SQL platform that happens to share the SQL Server connector).

_P.S. Please note that Microsoft customers cannot "reopen the issue". Only Microsoft personnel are so empowered. It's a customer-service process glitch that currently exists in the MicrosoftDocs workflow on GitHub._
