### ISSUE TITLE
Dataflow mapping to multi-choice instructions incorrect

### ISSUE THREAD

**Issue by YesWeCandrew** [MicrosoftDocs/powerquery-docs#343]
Under Known limitations in [Field mapping considerations for standard dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/get-best-of-standard-dataflows), the instructions to map a column to a Choices data type are unclear and appear not to work.

I have tried using a comma separated list of values as both a List type and as a concatenated comma separated string type in Power Query but neither work. [The instructions were added with this commit.](https://github.com/MicrosoftDocs/powerquery-docs/commit/b94b3227c03338196f4203bb23cee5e334df2b0a) by @bensack.

Other users are also unable to map to Multi-select / Choices data types using the method described in these docs. See suggestion here https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Dataflow-standard-v2-Integration-of-multiple-choices/td-p/872942

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 402b18e7-5542-37ae-08dd-f526c2d2b9c7
* Version Independent ID: c0ce55d5-81d3-04b5-170d-c3ca2fec48a2
* Content: [Field mapping considerations for standard dataflows - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/get-best-of-standard-dataflows#feedback)
* Content Source: [powerquery-docs/dataflows/get-best-of-standard-dataflows.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/get-best-of-standard-dataflows.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by ryanperrymba** [comment]
Hi, as a follow up on this issue, the instructions for mapping a standard, OOB column are also incomplete / incorrect. 

Example field is the Contact.Account lookup, which is possibly the most mapped OOB lookup in data migrations, but it appears is not readily mapped using dataflows.  The lookup field simply doesn't show up, even after adding an alternate key to the account table. A newly created lookup field however, does. How can one update the OOB Contact.Account lookup field definition to ensure it sees the alternate key and can be mapped, or otherwise make it appear in the mapping interface, as to be able to associate a contact with an account?

**Comment by DougKlopfenstein** [comment]
Hi @YesWeCandrew @ryanperrymba 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
