### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerquery-docs#371]
I think it would be beneficial to describe how this transformation works from query folding perspective.

Is it query folded or not query folded? Does the answer depend on the data source type?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba36059-c3f8-d871-c45c-6425979e82d2
* Version Independent ID: a7662d1d-5915-a921-711c-8e8085419ff0
* Content: [Query folding - Power Query](https://learn.microsoft.com/en-us/power-query/power-query-folding)
* Content Source: [powerquery-docs/power-query-folding.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/power-query-folding.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by ptyx507x** [comment]
Hey! Thanks for the feedback.

Query folding relies on two critical components:

- Data Source capabilities
- Connector folding definitions

This entails that for a particular data source, some things might fold with a particular connector but using the same connector with a different data source might not. For example, let's say that you connect to a version of SQL Server prior to 2008 R2, but you also connect to the latest version of SQL Server and when you try to fold some capabilities some of them might not fold because the data source doesn't accept some of the latest features / functions in SQL Server.

Things get more extensive when we try to analyze other connectors and data sources since each connector could translate a particular M query to something that is uniquely interpreted to a particular data source and is not treated the same as in other data sources, so that query folding logic is defined at the connector level.

This article particular just tries to provide the overview of what the concept of "Query folding" is and the rest of the articles that we have try to explain better how you can leverage and interpret query folding using tools like the query folding indicators and the query plan. Some links below:

- https://learn.microsoft.com/en-us/power-query/query-folding-examples
- https://learn.microsoft.com/en-us/power-query/step-folding-indicators
- https://learn.microsoft.com/en-us/power-query/query-plan

Hope this helps!

**Comment by ptyx507x** [comment]
#please-close

**Comment by VitalyMCT** [comment]
@ptyx507x Thanks for your response.

I understand the aspects you've outlined that are associated with query folding in general. I think they are well-described in the current article.

This issue was opened specifically for the transformation that does sorting. Unlike pretty much all other very common transformations it's listed in neither of these 2 sections:

> Transformations that can achieve folding
nor in
> Transformations that prevent folding

My recommendation is to list it in one of them. For instance, using your example of SQL Server, does sorting get folded into T-SQL via ORDER BY or does it not get folded? This is the aspect my customers would like to see documented.

**Comment by ptyx507x** [comment]
Thank you! We'll look at it internally and will be modifying this article.  I believe this is one of the articles that we initially imported from the Power BI documentation site, so it has quite a bit of information which is specific to Power BI as well beyond the scope of the list to be limited to only a specific connector.

**Comment by VitalyMCT** [comment]
Thanks @ptyx507x. Maybe you can keep this item open until it's processed.

**Comment by VitalyMCT** [comment]
Yes, I like your proposal. Basically the Power Query users need a way to know what's folding and what's not. Since it's very connector-specific, yes, it looks like putting the info in the connector documentation would be ideal.

**Comment by JasonWHowell** [comment]
@ptyx507x let's chat with @DougKlopfenstein . I think you have an email for this subject.

**Comment by DougKlopfenstein** [comment]
Hi @VitalyMCT 
Thanks for your dedication to our documentation. Unfortunately, at this time we don't have the resources to create and maintain the change you've asked for and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
