### ISSUE TITLE
Navigator window not displaying function input parameters

### ISSUE THREAD

**Issue by karunpoudel-chr** [MicrosoftDocs/powerquery-docs#388]
Using the provided `Table.ToNavigationTable` function, navigator window does not display function input parameters. According to the solution in [this post](https://community.powerbi.com/t5/Developer/Navigator-window-not-displaying-function-input-parameters-Custom/m-p/2958736), we need to remove `Preview.DelayColumn = itemNameColumn` line from `Table.ToNavigationTable`. I have verified that this is correct. 

Not sure if this PowerBI bug or is working as expected.

Mentioning this workaround in documentation would greatly help developer. They wouldn't have to waste lots of time trying to debug the issue and search in internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5bc95e-99a6-0d05-b3d5-c064daa417d0
* Version Independent ID: dfb79a5a-5419-44dc-389a-f4e46b5247c6
* Content: [Handling navigation for Power Query connectors - Power Query](https://learn.microsoft.com/en-us/power-query/handling-navigation-tables)
* Content Source: [powerquery-docs/handling-navigation-tables.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/handling-navigation-tables.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by JasonWHowell** [comment]
@mattmasson do you approve this proposed addition to the doc?

**Comment by DougKlopfenstein** [comment]
Hi @karunpoudel-chr 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
