### ISSUE TITLE
Was looking to find out how to specify the data type of a custom Power Query function

### ISSUE THREAD

**Issue by JerryDNYC** [MicrosoftDocs/powerquery-docs#390]
I was looking to see how to specify the data type a Power Query function produces so that for example ",type number" didn't have to be specified in the function call to the Table.AddColumn line of M Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adfb26bf-e0e4-fa66-409e-646c0b5ec2c6
* Version Independent ID: be67d882-0168-ea43-24aa-a3265552d983
* Content: [Using custom functions in Power Query - Power Query](https://learn.microsoft.com/en-us/power-query/custom-function?source=recommendations)
* Content Source: [powerquery-docs/custom-function.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/custom-function.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @JerryDNYC 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, we can help redirect you to the right support channel to get an answer to your question: [Power Query in Power BI](https://community.fabric.microsoft.com/t5/Power-Query/bd-p/power-bi-services). Because this issue does not relate to documentation, we are closing this issue. #please-close
