### ISSUE TITLE
How to prevent Formula FW issues

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerquery-docs#418]
I run into this problem from time to time:

Formula.Firewall: Query 'Query1' (step 'Source') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination

The thing is that I get the error when refreshing the report (in Power BI Desktop only, not the Power BI Service) and not when using the Power Query editor so it's kind of hard to find out what's wrong.

To solve the issue I sometimes divide my query into a second sub-query (since a sub-query always will be a partition of its own) and sometimes I do Table.Buffer(). 

The changes I would like in this documentation is to describe the most efficient way to solve the issues. I guess that also Table.StopFolding() should be able to use to prevent any problems with the FW (even when trying to combine data sources of different privacy level), but I haven't got that to work and doubts that the formula FW understands Table.StopFolding()

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf52bcc-93b4-7ffe-8ba6-1eba7acb7be1
* Version Independent ID: 4bcfbf05-8981-99c2-e736-d103e9126371
* Content: [Behind the scenes of the Data Privacy Firewall - Power Query](https://learn.microsoft.com/en-us/power-query/data-privacy-firewall)
* Content Source: [powerquery-docs/data-privacy-firewall.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/data-privacy-firewall.md)
* Service: **powerquery**
* GitHub Login: @ehrenMSFT
* Microsoft Alias: **ehvonleh**

**Comment by ehrenMSFT** [comment]
If you only see this when refreshing the PBI Desktop model, but not in the PQ Editor, then this is likely a known issue. It's caused by multiple concurrent background analysis evaluations canceling each other, resulting in the queries being partitioned incorrectly by the firewall. We're currently looking into a fix.

In the meantime, the most recent version of PBI Desktop should include a change that allows the refresh to succeed on retry. (Previously once it failed, it would keep failing no matter how many times you retried it.) Please let us know whether this works for you.

You can also work around this issue by turning off the data privacy firewall.

**Comment by erapade** [comment]
Tanks @ehrenMSFT. I have tried to log tickets a couple of times for this but never got this good information. 

As it looks like you have good insight into the formula FW, don't you think that using Table.StopFolding after querying a  public data source efficiently should protect from leaking organizational and/or private data and that the forums FW should adhere to this?

Concerning the possibilities of doing retries I didn't see any improvements and I instead solved the problem using Table.Buffer
