### ISSUE TITLE
Update Limitations and known issues section

### ISSUE THREAD

**Issue by DarinSpence** [MicrosoftDocs/powerquery-docs#435]
Database names that contain uppercase and lowercase letters fail.
TESTDATABASENAME - Seems to work
TestDataBaseName - Does not seem to work

This should be added as a Known Limitation in the documentation.
https://community.fabric.microsoft.com/t5/Issues/quot-Value-cannot-be-null-Parameter-name-source-quot-error-using/idi-p/3271135

**Comment by DougKlopfenstein** [comment]
Have you tried a possible fix mentioned here: [Potential solution for the Hyphens issue #444](https://github.com/MicrosoftDocs/powerquery-docs/issues/444)? Let us know if that fix works with this issue.

**Comment by DougKlopfenstein** [comment]
Hi @DarinSpence 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. Since we have not heard back from you for some time, we are closing this issue for now. But if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
