### ISSUE TITLE
Power Query refresh Lagging in simple steps

### ISSUE THREAD

**Issue by eduardo-suela-DEq** [MicrosoftDocs/powerquery-docs#453]
Advice on the page is very interesting, but there is lag in power query previews that shouldn't be happening
Or maybe I am not understanding how refresh works. (Just a far a away possibility)

When you have several queries calling each other.
There are a first and second query. The second is related with the first.
Go to the first query
Refresh the first query
Go to the second query
Go to the first step which is just the call to the first query. 
Refresh the the first step in the second query. Sometimes It takes ages!!!!

Thanks
Eduardo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a35602-5e1e-8a21-b3d7-c34404b4ae23
* Version Independent ID: 8d469d9b-1ee5-7c97-b7dd-d006385d6756
* Content: [Best practices when working with Power Query - Power Query](https://learn.microsoft.com/en-us/power-query/best-practices)
* Content Source: [powerquery-docs/best-practices.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/best-practices.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **miescobar**

**Comment by ehrenMSFT** [comment]
A couple points:

- When you explicitly refresh, the PQ Editor will re-evaluate the current step as well as all its dependencies. It's kind of like saying, "Don't rely on any cached results. Just bring me the latest data."
- In the PQ Editor, each query's preview is computed independently. Assume query B references query A. There's currently no optimization that utilizes A's preview when previewing B. The only thing that _is_ shared is a data source-level cache, which means that the data sources referenced by A can be cached when A is previewed, and that these cached results can be accessed when B is being previewed.

In Dataflows, however, there are features that allow you can store the results of A, so that once A is refreshed, B just gets the data that was already computed as part of A's refresh.

**Comment by eduardo-suela-DEq** [comment]
Are steps in a single query treated separatelly?
If so, splitting should be discouraged?

**Comment by ehrenMSFT** [comment]
Yes, step previews are also computed independently.

But in most cases, this doesn't mean you should put all your PQ code into a single, giant step.

**Comment by eduardo-suela-DEq** [comment]
I was afraid of the opposite. 
I like to split queries in important logical parts. Also naming important steps
If there is almost no diference, i will keep separating parts. (There is the source step added at each split)

**Comment by DougKlopfenstein** [comment]
Hi @eduardo-suela-DEq 
Thanks for the feedback. It appears that your questions have been answered. If you have more questions regarding how the product works, you can direct those questions to the dedicated support channels for the product you're using Power Query in. More information: [Power Query feedback](https://learn.microsoft.com/power-query/feedback).
