### ISSUE TITLE
No Authentication Diaglog

### ISSUE THREAD

**Issue by beckypeltz-hdrinc** [MicrosoftDocs/powerquery-docs#469]
[Enter feedback here]
I just tried out this HelloWorld project and I don't see an authentication diaglog in Power BI when I load it there

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 932383a1-a3d9-cbb2-b65c-756bf39c9d26
* Version Independent ID: 1e731e99-56d9-7dc7-2908-396260e9b4b0
* Content: [Creating your first connector - Hello World - Power Query](https://learn.microsoft.com/en-us/power-query/creating-first-connector)
* Content Source: [powerquery-docs/creating-first-connector.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/creating-first-connector.md)
* Service: **powerquery**
* GitHub Login: @ptyx507x
* Microsoft Alias: **miescobar**

**Comment by DougKlopfenstein** [comment]
Hi @beckypeltz-hdrinc 
Thanks for your feedback!. I just did a build of the HelloWorld example in the documentation. I then ran the new HelloWorld connector in Power BI and the authentication dialog opened asking for "Anonymous" authentication.

Since the HelloWorld example in the documentation appears to be working, you should ask for help from product support. For information about providing product feedback or getting customer support for Power Query, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback).

We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. #please-close
