### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by QuantuMatrix** [MicrosoftDocs/powerquery-docs#491]
This page is missing half of the instructions. I know how to create a primary key, alternate, and a dataflow.
What I'm looking for is directions that are directly stated in the title and subsequent text.
How do I connect my Dataverse table to a dataflow so that it updates the records (adds and deletes) every time the dataflow is refreshed?
Thanks for listening and I look forward to seeing the rest of the article when you publish it.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 742a9be8-5797-131b-3ea2-62759058384d
* Version Independent ID: 0d9b5a95-5bea-d4b3-b231-eca70101067b
* Content: [Sync your Excel data source with Dataverse using a dataflow - Power Query](https://learn.microsoft.com/en-us/power-query/dataflows/sync-excel-cds-dataflow)
* Content Source: [powerquery-docs/dataflows/sync-excel-cds-dataflow.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/main/powerquery-docs/dataflows/sync-excel-cds-dataflow.md)
* Service: **powerquery**
* GitHub Login: @bensack
* Microsoft Alias: **bensack**

**Comment by DougKlopfenstein** [comment]
Hi @QuantuMatrix 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
