### ISSUE TITLE
Does this page applies for Online or Desktop - Power BI?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/powerquery-docs#76]
Hi,
I have never used Power Query Editor Online, this doc and the screenshots in it are not pointing to desktop or online.

1. Does this page applies to Desktop or Online?
2. How do we access power query online? Is it only for any paid services only?

Better start the page like... 
"Power BI Desktop - Diagram view offers a visual way to prepare data in the Power Query editor - Desktop."

Instead of just...
"Diagram view offers a visual way to prepare data in the Power Query editor"

regards,
Singaravelu S
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cb61f83-9d14-2e3a-a2f3-6bd9b5a6f119
* Version Independent ID: 28157cb9-851d-3127-cdc9-00cd5aa7582f
* Content: [Diagram view (Preview)](https://docs.microsoft.com/en-us/power-query/diagram-view)
* Content Source: [powerquery-docs/diagram-view.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/diagram-view.md)
* Service: **powerquery**
* GitHub Login: @ptyx507
* Microsoft Alias: **v-miesco**

**Comment by heydh** [comment]
Thanks for your feedback. 

1. This page applies to Power Query Online (and not Desktop). 
2. You can access this feature (Diagram View) within Power BI dataflows or Power Apps dataflows. For example: With respect to Power BI, it is available within Power BI pro and Power BI premium. With respect to Power Apps, its available within the per app or per user plan. 

We wanted the documentation to be generic because Power Query Online is available within several products such as Power BI, Power Apps and more. Hope this helps!
