### ISSUE TITLE
CDS connection doesn't show some tables?

### ISSUE THREAD

**Issue by itsdeshpande** [MicrosoftDocs/powerquery-docs#79]
Is there a reason why some tables are not shown when you connect to an online instance? I don't see "Role" and "SystemUserRoles" tables in there. Is this by design, or what is the reason. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cd378b5-7f88-da23-7060-e933bdebf46c
* Version Independent ID: 6f10e7c8-e277-c14a-01cd-c1287da3dee6
* Content: [Power Query Common Data Service connector](https://docs.microsoft.com/en-us/power-query/connectors/commondataservice)
* Content Source: [powerquery-docs/Connectors/CommonDataService.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/CommonDataService.md)
* Service: **powerquery**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **v-douklo**

**Comment by DougKlopfenstein** [comment]
Hi @itsdeshpande -
This appears to be a customer support issue rather than a documentation issue. For information about Power Query support, go to [Power Query feedback](https://docs.microsoft.com/power-query/feedback). For information about Power Query connector support, go to [Power Query connector feedback](https://docs.microsoft.com/power-query/connectors/connectorfeedback).
