### ISSUE TITLE
npgsql latest versions compatibility

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerquery-docs#92]
is it(following statement) still the case or do you have any update on compatibility with latest versions of npgsql?
We recommend NpgSQL 4.0.10. NpgSQL 4.1 and up won't work due to .NET version incompatibilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f05c74-8262-6610-bd9e-efe4f112bbe1
* Version Independent ID: 09570cd3-3a8b-18c6-da4c-46beada3a387
* Content: [Power Query PostgreSQL connector](https://docs.microsoft.com/en-us/power-query/connectors/postgresql)
* Content Source: [powerquery-docs/Connectors/PostgreSQL.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/Connectors/PostgreSQL.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @mganeshphani 
Sorry it has taken so long to get to your comment. The Power Query PostgreSQL connector prerequisite section has been updated several times since you posted this issue. This issue is being closed as "stale", but if you think that other changes need to be made to the prerequisite section for more clarity, please reopen this issue and let us know what changes or clarifications you would like to see.
