### ISSUE TITLE
Example for "Putting It All Together" in "Wait-Retry Pattern" may lead to unintentional side effect

### ISSUE THREAD

**Issue by cjlynch12** [MicrosoftDocs/powerquery-docs#93]
The example in the documentation under the "Putting It All Together" section may lead to an unintentional bug.

From my testing it appears that if you use the code as-is from the example, `Web.Contents` calls are duplicated (ignoring the use of `Binary.Buffer`).

The solution for me was to replace:

`actualResult = if status = 500 then null else buffered`

with `actualResult = if buffered <> null and status = 500 then null else buffered`

full fixed example:
```
let
    waitForResult = Value.WaitFor(
        (iteration) =>
            let
                result = Web.Contents(url, [ManualStatusHandling = {500}]), 
                buffered = Binary.Buffer(result),
                status = Value.Metadata(result)[Response.Status],
                actualResult = if buffered <> null and status = 500 then null else buffered
            in
                actualResult,
        (iteration) => #duration(0, 0, 0, Number.Power(2, iteration)),
        5)
in
    waitForResult,
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e8ea07-c37a-f246-dc5b-ef434f4b097b
* Version Independent ID: cf8ff1f9-617a-a605-fad0-28e81123a660
* Content: [Using the wait-retry pattern in Power Query connectors](https://docs.microsoft.com/en-us/power-query/waitretry)
* Content Source: [powerquery-docs/WaitRetry.md](https://github.com/MicrosoftDocs/powerquery-docs/blob/master/powerquery-docs/WaitRetry.md)
* Service: **powerquery**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by JasonWHowell** [comment]
Please ignore (I'm using bot automation to add labels). #please-open

**Comment by DougKlopfenstein** [comment]
Hi @cjlynch12 
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made since the creation of this issue, and the timeline for resolution may vary based on resourcing, so we've created an internal work item to incorporate your suggestions. We are closing this issue for now, but feel free to comment here as necessary. #please-close
